import pandas as pd


print('\n                 file: First_steps_with_data')
print('\n прочитаем данные для обработки')
students_performance = pd.read_csv('/home/nikolay/PycharmProjects/Pandas_Students_Performance/downloads/StudentsPerformance.csv')
print('\n исследуем данные файла')
print('\n форма таблицы (строк, колонок)', students_performance.shape,'\nразмер таблицы (строк*колонок)', students_performance.size)
print('\n отобразим первые 5 строк таблицы на экран')
print(students_performance.head(5))
print('\n посмотрим статистику по данным')
print(students_performance.describe())
print('\n посмотрим типы данных таблицы')
print(students_performance.dtypes)
print('\n сгруппируем данные по gender и посчитаем среднее значение writing score')
print(students_performance.groupby('gender').aggregate({'writing score': 'mean'}))
print('\n отберем первые 5 строк и 3 колонки')
print(students_performance.iloc[0:5, 0:3])
print('\n или строки 0 (первая), 3, 10, колонки 0 (первая), 5, -1 (последняя)')
print(students_performance.iloc[[0, 3, 10], [0, 5, -1]])
print('\n создадим маленький датафрейм из следующих пяти строк')
students_performance_with_names = students_performance.iloc[[0, 3, 4, 7, 8]]
print(students_performance_with_names)
print('\n присвоим индексам созданного датафрейма имена')
students_performance_with_names.index = ['Cercey', 'Taywin', 'Gregor', 'Joffray', 'Ilyn Payne']
print(students_performance_with_names)
print('\n отберем несколько человек из списка по их именам')
print(students_performance_with_names.loc[['Cercey', 'Joffray'], ['gender', 'writing score']])
print('\n отберем серию (1 колонку) из созданного датафрейма')
print(students_performance_with_names.iloc[:, 0])
print('\n выведем серию [] и датафрейм первой колонки [[]]')
print('\n Серия из первоей колонки\n', students_performance_with_names['gender'].head(3))
print('\n Датафрейм из первоей колонки\n', students_performance[['gender']].head(3))
print('\n выведем 5 строк данных колонки gender')
print(students_performance.gender.head(5))
